/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishesRouteImport } from './routes/wishes'
import { Route as WishbookRouteImport } from './routes/wishbook'
import { Route as TarotRouteImport } from './routes/tarot'
import { Route as StarmapRouteImport } from './routes/starmap'
import { Route as MoodboardRouteImport } from './routes/moodboard'
import { Route as MatchaRouteImport } from './routes/matcha'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const WishesRoute = WishesRouteImport.update({
  id: '/wishes',
  path: '/wishes',
  getParentRoute: () => rootRouteImport,
} as any)
const WishbookRoute = WishbookRouteImport.update({
  id: '/wishbook',
  path: '/wishbook',
  getParentRoute: () => rootRouteImport,
} as any)
const TarotRoute = TarotRouteImport.update({
  id: '/tarot',
  path: '/tarot',
  getParentRoute: () => rootRouteImport,
} as any)
const StarmapRoute = StarmapRouteImport.update({
  id: '/starmap',
  path: '/starmap',
  getParentRoute: () => rootRouteImport,
} as any)
const MoodboardRoute = MoodboardRouteImport.update({
  id: '/moodboard',
  path: '/moodboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchaRoute = MatchaRouteImport.update({
  id: '/matcha',
  path: '/matcha',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calendar': typeof CalendarRoute
  '/matcha': typeof MatchaRoute
  '/moodboard': typeof MoodboardRoute
  '/starmap': typeof StarmapRoute
  '/tarot': typeof TarotRoute
  '/wishbook': typeof WishbookRoute
  '/wishes': typeof WishesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calendar': typeof CalendarRoute
  '/matcha': typeof MatchaRoute
  '/moodboard': typeof MoodboardRoute
  '/starmap': typeof StarmapRoute
  '/tarot': typeof TarotRoute
  '/wishbook': typeof WishbookRoute
  '/wishes': typeof WishesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calendar': typeof CalendarRoute
  '/matcha': typeof MatchaRoute
  '/moodboard': typeof MoodboardRoute
  '/starmap': typeof StarmapRoute
  '/tarot': typeof TarotRoute
  '/wishbook': typeof WishbookRoute
  '/wishes': typeof WishesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/calendar'
    | '/matcha'
    | '/moodboard'
    | '/starmap'
    | '/tarot'
    | '/wishbook'
    | '/wishes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/calendar'
    | '/matcha'
    | '/moodboard'
    | '/starmap'
    | '/tarot'
    | '/wishbook'
    | '/wishes'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/calendar'
    | '/matcha'
    | '/moodboard'
    | '/starmap'
    | '/tarot'
    | '/wishbook'
    | '/wishes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CalendarRoute: typeof CalendarRoute
  MatchaRoute: typeof MatchaRoute
  MoodboardRoute: typeof MoodboardRoute
  StarmapRoute: typeof StarmapRoute
  TarotRoute: typeof TarotRoute
  WishbookRoute: typeof WishbookRoute
  WishesRoute: typeof WishesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishes': {
      id: '/wishes'
      path: '/wishes'
      fullPath: '/wishes'
      preLoaderRoute: typeof WishesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishbook': {
      id: '/wishbook'
      path: '/wishbook'
      fullPath: '/wishbook'
      preLoaderRoute: typeof WishbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarot': {
      id: '/tarot'
      path: '/tarot'
      fullPath: '/tarot'
      preLoaderRoute: typeof TarotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/starmap': {
      id: '/starmap'
      path: '/starmap'
      fullPath: '/starmap'
      preLoaderRoute: typeof StarmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moodboard': {
      id: '/moodboard'
      path: '/moodboard'
      fullPath: '/moodboard'
      preLoaderRoute: typeof MoodboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matcha': {
      id: '/matcha'
      path: '/matcha'
      fullPath: '/matcha'
      preLoaderRoute: typeof MatchaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CalendarRoute: CalendarRoute,
  MatchaRoute: MatchaRoute,
  MoodboardRoute: MoodboardRoute,
  StarmapRoute: StarmapRoute,
  TarotRoute: TarotRoute,
  WishbookRoute: WishbookRoute,
  WishesRoute: WishesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
